src/playground_app/urls.py
from django.urls import path

from playground_app.views import index
from playground_app.views import page

app_name = "app"

urlpatterns = [
    path('', index, name='index'),
    path('page-<str:numero>', page, name="page"),
]

src/playground_project/urls.py
from django.contrib import admin
from django.urls import path, include
from playground_project.views import index

urlpatterns = [
    path('admin/', admin.site.urls),
    path("app/", include("playground_app.urls")),
    path("", index, name="index"),
]

src/playground_app/models.py
from django.db import models

# Create your models here.

src/playground_app/views.py
from django.shortcuts import render


# Create your views here.
def index(request):
    return render(request, "playground_app/index.html", context={"name": "App Context"})


def page(request, numero):
    if numero in ["01", "02", "03"]:
        return render(request, f"playground_app/page_{numero}.html", context={"numero": numero})
    else:
        return render(request, "playground_app/page_not_found.html", context={"numero": numero})

src/playground_project/views.py
from django.shortcuts import render


# Create your views here.
def index(request):
    return render(request, "playground_project/index.html", context={"name": "Project Context"})

src/playground_app/templates/playground_app/Page_03.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Page 03</title>
    <link rel="stylesheet" href="{% static '' %}">
</head>
<body>
<h1>Page 3</h1>
{{ numero }}
</body>
</html>

src/playground_app/templates/playground_app/index.html
{% load static %}
<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <title>App Page</title>
    <link rel="stylesheet" href="{% static 'playground_app/style.css' %}">
</head>
<body>
    <h1>App Page</h1>
    {{ name }}
    <a href="{% url 'index' %}">Project Index</a>
</body>
</html>

src/playground_app/templates/playground_app/page_01.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Page 01</title>
    <link rel="stylesheet" href="{% static '' %}">
</head>
<body>
<h1>Page 1</h1>
{{ numero }}
</body>
</html>

src/playground_app/templates/playground_app/page_02.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Page 02</title>
    <link rel="stylesheet" href="{% static '' %}">
</head>
<body>
<h1>Page 2</h1>
{{ numero }}
</body>
</html>

src/playground_app/templates/playground_app/page_not_found.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Page Not Found</title>
    <link rel="stylesheet" href="{% static 'playground_app/style_blue.css' %}">
</head>
<body>
<h1>Page Not Found</h1>
{{ numero }}
</body>
</html>

src/playground_project/templates/playground_project/index.html
{% load static %}
<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <title>Project Page</title>
    <link rel="stylesheet" href="{% static 'playground_project/style.css' %}">
</head>
<body>
    <h1>Project Page</h1>
    {{ name }}
    <a href="{% url 'app:index' %}">App Index</a>
</body>
</html>